name: bootc build

on:
  push:
    branches: main
  pull_request:
    branches: main
    
jobs:
  login:
    runs-on: self-hosted
    steps:
      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Login to registry.redhat.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHN_USERNAME }}
          password: ${{ secrets.RHN_ROBOT_TOKEN }}


      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: anrussel/mine-rhel9-bootc
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          build-args: |
            rootpw=${{ secrets.ROOTPW }}

