name: Podman ubild

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.MINE}}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: srv01-mine-01

    steps:
    - uses: actions/checkout@v4
    - name: Podman build now
      run: podman build --build-arg "sshpubkey=${{ env.MY_PUBKEY }}" -f Containerfile -t mine-rhel9-bootc
