name: Podman bootc build
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: srv01-mine-01

    steps:
    - uses: actions/checkout@v4
    - name: Podman build now
      run: podman build --build-arg rootpw='S{{ secrets.ROOT_PW }}'   -f Containerfile -t quay.io/anrussel/mine-rhel9-bootc
    - name: Login Quay
      run: podman login -u='${{ secrets.QUAY_USERNAME }}' -p='${{ secrets.QUAY_ROBOT_TOKEN }}' quay.io
    - name: Push to Quay
      run: podman push quay.io/anrussel/mine-rhel9-bootc
