name: Podman bootc build
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:


  login:
    runs-on: srv01-mine-01
    
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          
          
  build:
    runs-on: srv01-mine-01

    steps:
    - uses: actions/checkout@v4
    - name: Podman build now
      run: podman build -f Containerfile -t mine-rhel9-bootc

