name: Podman bootc build
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: srv01-mine-01

    steps:
    - uses: actions/checkout@v4
    - name: Podman build now
      run: podman build -f Containerfile -t mine-rhel9-bootc
