name: Build Test
  
on:
  push:
    branches: [ "test" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Login registry.redhat.io
      run: podman login -u='${{ secrets.RHN_USERNAME }}' -p='${{ secrets.RHN_ROBOT_TOKEN }}' registry.redhat.io
    - name: Podman build now
      run: podman build -f Containerfile -t quay.io/anrussel/mine-rhel9-bootc:test
    - name: Login Quay
      run: podman login -u='${{ secrets.QUAY_USERNAME }}' -p='${{ secrets.QUAY_ROBOT_TOKEN }}' quay.io
    - name: Push to Quay
      run: podman push quay.io/anrussel/mine-rhel9-bootc:test
