name: test workflow

on:
  push:
    branches: [dev,test,prod]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Run 
        run: |
          echo "${GITHUB_REF##*/}"
